<?php

use Illuminate\Database\Seeder;

class KecamatanTableSeeder extends Seeder {

	public function run () {

		DB::table('kecamatan')->delete();

		DB::table('kecamatan')->insert([
				['kabupaten_id' => '1', 'nama_kecamatan' => 'Bambang Lipuro', 'slug_nama' => str_slug('Bambang Lipuro'), 'created_at' => new DateTime, 'updated_at' => new DateTime],
				['kabupaten_id' => '1', 'nama_kecamatan' => 'Banguntapan', 'slug_nama' => str_slug('Banguntapan'), 'created_at' => new DateTime, 'updated_at' => new DateTime],
				['kabupaten_id' => '1', 'nama_kecamatan' => 'Bantul', 'slug_nama' => str_slug('Bantul'), 'created_at' => new DateTime, 'updated_at' => new DateTime],
				['kabupaten_id' => '1', 'nama_kecamatan' => 'Dlingo', 'slug_nama' => str_slug('Dlingo'), 'created_at' => new DateTime, 'updated_at' => new DateTime],
				['kabupaten_id' => '1', 'nama_kecamatan' => 'Imogiri', 'slug_nama' => str_slug('Imogiri'), 'created_at' => new DateTime, 'updated_at' => new DateTime],
				['kabupaten_id' => '1', 'nama_kecamatan' => 'Jetis', 'slug_nama' => str_slug('Jetis'), 'created_at' => new DateTime, 'updated_at' => new DateTime],
				['kabupaten_id' => '1', 'nama_kecamatan' => 'Kasihan', 'slug_nama' => str_slug('Kasihan'), 'created_at' => new DateTime, 'updated_at' => new DateTime],
				['kabupaten_id' => '1', 'nama_kecamatan' => 'Kretek', 'slug_nama' => str_slug('Kretek'), 'created_at' => new DateTime, 'updated_at' => new DateTime],
				['kabupaten_id' => '1', 'nama_kecamatan' => 'Pajangan', 'slug_nama' => str_slug('Pajangan'), 'created_at' => new DateTime, 'updated_at' => new DateTime],
				['kabupaten_id' => '1', 'nama_kecamatan' => 'Pandak', 'slug_nama' => str_slug('Pandak'), 'created_at' => new DateTime, 'updated_at' => new DateTime],
				['kabupaten_id' => '1', 'nama_kecamatan' => 'Piyungan', 'slug_nama' => str_slug('Piyungan'), 'created_at' => new DateTime, 'updated_at' => new DateTime],
				['kabupaten_id' => '1', 'nama_kecamatan' => 'Pleret', 'slug_nama' => str_slug('Pleret'), 'created_at' => new DateTime, 'updated_at' => new DateTime],
				['kabupaten_id' => '1', 'nama_kecamatan' => 'Pundong', 'slug_nama' => str_slug('Pundong'), 'created_at' => new DateTime, 'updated_at' => new DateTime],
				['kabupaten_id' => '1', 'nama_kecamatan' => 'Sanden', 'slug_nama' => str_slug('Sanden'), 'created_at' => new DateTime, 'updated_at' => new DateTime],
				['kabupaten_id' => '1', 'nama_kecamatan' => 'Sedayu', 'slug_nama' => str_slug('Sedayu'), 'created_at' => new DateTime, 'updated_at' => new DateTime],
				['kabupaten_id' => '1', 'nama_kecamatan' => 'Sewon', 'slug_nama' => str_slug('Sewon'),  'created_at' => new DateTime, 'updated_at' => new DateTime],
				['kabupaten_id' => '1', 'nama_kecamatan' => 'Srandakan', 'slug_nama' => str_slug('Srandakan'), 'created_at' => new DateTime, 'updated_at' => new DateTime],
				['kabupaten_id' => '2', 'nama_kecamatan' => 'Gedang Sari', 'slug_nama' => str_slug('Gedang Sari'), 'created_at' => new DateTime, 'updated_at' => new DateTime],
				['kabupaten_id' => '2', 'nama_kecamatan' => 'Girisubo', 'slug_nama' => str_slug('Girisubo'), 'created_at' => new DateTime, 'updated_at' => new DateTime],
				['kabupaten_id' => '2', 'nama_kecamatan' => 'Karangmojo', 'slug_nama' => str_slug('Karangmojo'), 'created_at' => new DateTime, 'updated_at' => new DateTime],
				['kabupaten_id' => '2', 'nama_kecamatan' => 'Ngawen', 'slug_nama' => str_slug('Ngawen'), 'created_at' => new DateTime, 'updated_at' => new DateTime],
				['kabupaten_id' => '2', 'nama_kecamatan' => 'Nglipar', 'slug_nama' => str_slug('Nglipar'), 'created_at' => new DateTime, 'updated_at' => new DateTime],
				['kabupaten_id' => '2', 'nama_kecamatan' => 'Paliyan', 'slug_nama' => str_slug('Paliyan'), 'created_at' => new DateTime, 'updated_at' => new DateTime],
				['kabupaten_id' => '2', 'nama_kecamatan' => 'Panggang', 'slug_nama' => str_slug('Panggang'), 'created_at' => new DateTime, 'updated_at' => new DateTime],
				['kabupaten_id' => '2', 'nama_kecamatan' => 'Patuk', 'slug_nama' => str_slug('Patuk'), 'created_at' => new DateTime, 'updated_at' => new DateTime],
				['kabupaten_id' => '2', 'nama_kecamatan' => 'Playen', 'slug_nama' => str_slug('Playen'), 'created_at' => new DateTime, 'updated_at' => new DateTime],
				['kabupaten_id' => '2', 'nama_kecamatan' => 'Ponjong', 'slug_nama' => str_slug('Ponjong'), 'created_at' => new DateTime, 'updated_at' => new DateTime],
				['kabupaten_id' => '2', 'nama_kecamatan' => 'Purwosari', 'slug_nama' => str_slug('Purwosari'), 'created_at' => new DateTime, 'updated_at' => new DateTime],
				['kabupaten_id' => '2', 'nama_kecamatan' => 'Rongkop', 'slug_nama' => str_slug('Rongkop'), 'created_at' => new DateTime, 'updated_at' => new DateTime],
				['kabupaten_id' => '2', 'nama_kecamatan' => 'Sapto Sari', 'slug_nama' => str_slug('Sapto Sari'), 'created_at' => new DateTime, 'updated_at' => new DateTime],
				['kabupaten_id' => '2', 'nama_kecamatan' => 'Semanu', 'slug_nama' => str_slug('Semanu'), 'created_at' => new DateTime, 'updated_at' => new DateTime],
				['kabupaten_id' => '2', 'nama_kecamatan' => 'Semin', 'slug_nama' => str_slug('Semin'), 'created_at' => new DateTime, 'updated_at' => new DateTime],
				['kabupaten_id' => '2', 'nama_kecamatan' => 'Tanjungsari', 'slug_nama' => str_slug('Tanjungsari'), 'created_at' => new DateTime, 'updated_at' => new DateTime],
				['kabupaten_id' => '2', 'nama_kecamatan' => 'Tepus', 'slug_nama' => str_slug('Tepus'), 'created_at' => new DateTime, 'updated_at' => new DateTime],
				['kabupaten_id' => '2', 'nama_kecamatan' => 'Wonosari', 'slug_nama' => str_slug('Wonosari'), 'created_at' => new DateTime, 'updated_at' => new DateTime],
				['kabupaten_id' => '3', 'nama_kecamatan' => 'Galur', 'slug_nama' => str_slug('Galur'), 'created_at' => new DateTime, 'updated_at' => new DateTime],
				['kabupaten_id' => '3', 'nama_kecamatan' => 'Girimulyo', 'slug_nama' => str_slug('Girimulyo'), 'created_at' => new DateTime, 'updated_at' => new DateTime],
				['kabupaten_id' => '3', 'nama_kecamatan' => 'Kalibawang', 'slug_nama' => str_slug('Kalibawang'), 'created_at' => new DateTime, 'updated_at' => new DateTime],
				['kabupaten_id' => '3', 'nama_kecamatan' => 'Kokap', 'slug_nama' => str_slug('Kokap'), 'created_at' => new DateTime, 'updated_at' => new DateTime],
				['kabupaten_id' => '3', 'nama_kecamatan' => 'Lendah', 'slug_nama' => str_slug('Lendah'), 'created_at' => new DateTime, 'updated_at' => new DateTime],
				['kabupaten_id' => '3', 'nama_kecamatan' => 'Nanggulan', 'slug_nama' => str_slug('Nanggulan'), 'created_at' => new DateTime, 'updated_at' => new DateTime],
				['kabupaten_id' => '3', 'nama_kecamatan' => 'Panjatan', 'slug_nama' => str_slug('Panjatan'), 'created_at' => new DateTime, 'updated_at' => new DateTime],
				['kabupaten_id' => '3', 'nama_kecamatan' => 'Pengasih', 'slug_nama' => str_slug('Pengasih'), 'created_at' => new DateTime, 'updated_at' => new DateTime],
				['kabupaten_id' => '3', 'nama_kecamatan' => 'Samigaluh', 'slug_nama' => str_slug('Samigaluh'), 'created_at' => new DateTime, 'updated_at' => new DateTime],
				['kabupaten_id' => '3', 'nama_kecamatan' => 'Sentolo', 'slug_nama' => str_slug('Sentolo'), 'created_at' => new DateTime, 'updated_at' => new DateTime],
				['kabupaten_id' => '3', 'nama_kecamatan' => 'Temon', 'slug_nama' => str_slug('Temon'), 'created_at' => new DateTime, 'updated_at' => new DateTime],
				['kabupaten_id' => '3', 'nama_kecamatan' => 'Wates', 'slug_nama' => str_slug('Wates'), 'created_at' => new DateTime, 'updated_at' => new DateTime],
				['kabupaten_id' => '4', 'nama_kecamatan' => 'Berbah', 'slug_nama' => str_slug('Berbah'), 'created_at' => new DateTime, 'updated_at' => new DateTime],
				['kabupaten_id' => '4', 'nama_kecamatan' => 'Cangkringan', 'slug_nama' => str_slug('Cangkringan'), 'created_at' => new DateTime, 'updated_at' => new DateTime],
				['kabupaten_id' => '4', 'nama_kecamatan' => 'Depok', 'slug_nama' => str_slug('Depok'), 'created_at' => new DateTime, 'updated_at' => new DateTime],
				['kabupaten_id' => '4', 'nama_kecamatan' => 'Gamping', 'slug_nama' => str_slug('Gamping'), 'created_at' => new DateTime, 'updated_at' => new DateTime],
				['kabupaten_id' => '4', 'nama_kecamatan' => 'Godean', 'slug_nama' => str_slug('Godean'), 'created_at' => new DateTime, 'updated_at' => new DateTime],
				['kabupaten_id' => '4', 'nama_kecamatan' => 'Kalasan', 'slug_nama' => str_slug('Kalasan'), 'created_at' => new DateTime, 'updated_at' => new DateTime],
				['kabupaten_id' => '4', 'nama_kecamatan' => 'Minggir', 'slug_nama' => str_slug('Minggir'), 'created_at' => new DateTime, 'updated_at' => new DateTime],
				['kabupaten_id' => '4', 'nama_kecamatan' => 'Mlati', 'slug_nama' => str_slug('Mlati'), 'created_at' => new DateTime, 'updated_at' => new DateTime],
				['kabupaten_id' => '4', 'nama_kecamatan' => 'Moyudan', 'slug_nama' => str_slug('Moyudan'), 'created_at' => new DateTime, 'updated_at' => new DateTime],
				['kabupaten_id' => '4', 'nama_kecamatan' => 'Ngaglik', 'slug_nama' => str_slug('Ngaglik'), 'created_at' => new DateTime, 'updated_at' => new DateTime],
				['kabupaten_id' => '4', 'nama_kecamatan' => 'Ngemplak', 'slug_nama' => str_slug('Ngemplak'), 'created_at' => new DateTime, 'updated_at' => new DateTime],
				['kabupaten_id' => '4', 'nama_kecamatan' => 'Pakem', 'slug_nama' => str_slug('Pakem'), 'created_at' => new DateTime, 'updated_at' => new DateTime],
				['kabupaten_id' => '4', 'nama_kecamatan' => 'Prambanan', 'slug_nama' => str_slug('Prambanan'), 'created_at' => new DateTime, 'updated_at' => new DateTime],
				['kabupaten_id' => '4', 'nama_kecamatan' => 'Seyegan', 'slug_nama' => str_slug('Seyegan'), 'created_at' => new DateTime, 'updated_at' => new DateTime],
				['kabupaten_id' => '4', 'nama_kecamatan' => 'Sleman', 'slug_nama' => str_slug('Sleman'), 'created_at' => new DateTime, 'updated_at' => new DateTime],
				['kabupaten_id' => '4', 'nama_kecamatan' => 'Tempel', 'slug_nama' => str_slug('Tempel'), 'created_at' => new DateTime, 'updated_at' => new DateTime],
				['kabupaten_id' => '4', 'nama_kecamatan' => 'Turi', 'slug_nama' => str_slug('Turi'), 'created_at' => new DateTime, 'updated_at' => new DateTime],
				['kabupaten_id' => '5', 'nama_kecamatan' => 'Danurejan', 'slug_nama' => str_slug('Danurejan'), 'created_at' => new DateTime, 'updated_at' => new DateTime],
				['kabupaten_id' => '5', 'nama_kecamatan' => 'Gedong Tengen', 'slug_nama' => str_slug('Gedong Tengen'), 'created_at' => new DateTime, 'updated_at' => new DateTime],
				['kabupaten_id' => '5', 'nama_kecamatan' => 'Gondokusuman', 'slug_nama' => str_slug('Gondokusuman'), 'created_at' => new DateTime, 'updated_at' => new DateTime],
				['kabupaten_id' => '5', 'nama_kecamatan' => 'Gondomanan', 'slug_nama' => str_slug('Gondomanan'), 'created_at' => new DateTime, 'updated_at' => new DateTime],
				['kabupaten_id' => '5', 'nama_kecamatan' => 'Jetis', 'slug_nama' => str_slug('Jetis'), 'created_at' => new DateTime, 'updated_at' => new DateTime],
				['kabupaten_id' => '5', 'nama_kecamatan' => 'Kotagede', 'slug_nama' => str_slug('Kotagede'), 'created_at' => new DateTime, 'updated_at' => new DateTime],
				['kabupaten_id' => '5', 'nama_kecamatan' => 'Kraton', 'slug_nama' => str_slug('Kraton'), 'created_at' => new DateTime, 'updated_at' => new DateTime],
				['kabupaten_id' => '5', 'nama_kecamatan' => 'Mantrijeron', 'slug_nama' => str_slug('Mantrijeron'), 'created_at' => new DateTime, 'updated_at' => new DateTime],
				['kabupaten_id' => '5', 'nama_kecamatan' => 'Mergangsan', 'slug_nama' => str_slug('Mergangsan'), 'created_at' => new DateTime, 'updated_at' => new DateTime],
				['kabupaten_id' => '5', 'nama_kecamatan' => 'Ngampilan', 'slug_nama' => str_slug('Ngampilan'), 'created_at' => new DateTime, 'updated_at' => new DateTime],
				['kabupaten_id' => '5', 'nama_kecamatan' => 'Pakualaman', 'slug_nama' => str_slug('Pakualaman'), 'created_at' => new DateTime, 'updated_at' => new DateTime],
				['kabupaten_id' => '5', 'nama_kecamatan' => 'Tegalrejo', 'slug_nama' => str_slug('Tegalrejo'), 'created_at' => new DateTime, 'updated_at' => new DateTime],
				['kabupaten_id' => '5', 'nama_kecamatan' => 'Umbulharjo', 'slug_nama' => str_slug('Umbulharjo'), 'created_at' => new DateTime, 'updated_at' => new DateTime],
				['kabupaten_id' => '5', 'nama_kecamatan' => 'Wirobrajan', 'slug_nama' => str_slug('Wirobrajan'), 'created_at' => new DateTime, 'updated_at' => new DateTime]
			]
		);
	}
}